In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv('../additional_material/datasets/week9/housing.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [48]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [49]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [50]:
df.sample(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1312,1313,60,RL,NaN,9572,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,302000
1250,1251,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
837,838,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,WD,Normal,100000
169,170,20,RL,NaN,16669,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2006,WD,Normal,228000
1139,1140,30,RL,98.0,8731,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,144000

In [51]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [52]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [54]:

categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(f"We have {len(categorical_cols)} categorical variables to check.")

drop_low_variance = []

for col in categorical_cols:
    top_pct = df[col].value_counts(normalize=True).iloc[0]
    
    if top_pct > 0.87:
        print(f"DROP {col}: {top_pct:.1%} of rows are '{df[col].mode()[0]}'")
        drop_low_variance.append(col)

df = df.drop(columns=drop_low_variance)
df.info()

We have 43 categorical variables to check.
DROP Street: 99.6% of rows are 'Pave'
DROP LandContour: 89.8% of rows are 'Lvl'
DROP Utilities: 99.9% of rows are 'AllPub'
DROP LandSlope: 94.7% of rows are 'Gtl'
DROP Condition2: 99.0% of rows are 'Norm'
DROP RoofMatl: 98.2% of rows are 'CompShg'
DROP ExterCond: 87.8% of rows are 'TA'
DROP BsmtCond: 92.1% of rows are 'TA'
DROP BsmtFinType2: 88.3% of rows are 'Unf'
DROP Heating: 97.8% of rows are 'GasA'
DROP CentralAir: 93.5% of rows are 'Y'
DROP Electrical: 91.4% of rows are 'SBrkr'
DROP Functional: 93.2% of rows are 'Typ'
DROP GarageQual: 95.1% of rows are 'TA'
DROP GarageCond: 96.2% of rows are 'TA'
DROP PavedDrive: 91.8% of rows are 'Y'
DROP MiscFeature: 90.7% of rows are 'Shed'
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 64 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LotConfig      1460 non-null   object
 8   Neighborhood   1460 non-null   object
 9   Condition1     1460 non-null   object
 10  BldgType       1460 non-null   object
 11  HouseStyle     1460 non-null   object
 12  OverallQual    1460 non-null   int64
 13  OverallCond    1460 non-null   int64
 14  YearBuilt      1460 non-null   int64
 15  YearRemodAdd   1460 non-null   int64
 16  RoofStyle      1460 non-null   object
 17  Exterior1st    1460 non-null   object
 18  Exterior2nd    1460 non-null   object
 19  MasVnrType     588 non-null    object
 20  MasVnrArea     1452 non-null   float64
 21  ExterQual      1460 non-null   object
 22  Foundation     1460 non-null   object
 23  BsmtQual       1423 non-null   object
 24  BsmtExposure   1422 non-null   object
 25  BsmtFinType1   1423 non-null   object
 26  BsmtFinSF1     1460 non-null   int64
 27  BsmtFinSF2     1460 non-null   int64
 28  BsmtUnfSF      1460 non-null   int64
 29  TotalBsmtSF    1460 non-null   int64
 30  HeatingQC      1460 non-null   object
 31  1stFlrSF       1460 non-null   int64
 32  2ndFlrSF       1460 non-null   int64
 33  LowQualFinSF   1460 non-null   int64
 34  GrLivArea      1460 non-null   int64
 35  BsmtFullBath   1460 non-null   int64
 36  BsmtHalfBath   1460 non-null   int64
 37  FullBath       1460 non-null   int64
 38  HalfBath       1460 non-null   int64
 39  BedroomAbvGr   1460 non-null   int64
 40  KitchenAbvGr   1460 non-null   int64
 41  KitchenQual    1460 non-null   object
 42  TotRmsAbvGrd   1460 non-null   int64
 43  Fireplaces     1460 non-null   int64
 44  FireplaceQu    770 non-null    object
 45  GarageType     1379 non-null   object
 46  GarageYrBlt    1379 non-null   float64
 47  GarageFinish   1379 non-null   object
 48  GarageCars     1460 non-null   int64
 49  GarageArea     1460 non-null   int64
 50  WoodDeckSF     1460 non-null   int64
 51  OpenPorchSF    1460 non-null   int64
 52  EnclosedPorch  1460 non-null   int64
 53  3SsnPorch      1460 non-null   int64
 54  ScreenPorch    1460 non-null   int64
 55  PoolArea       1460 non-null   int64
 56  PoolQC         7 non-null      object
 57  Fence          281 non-null    object
 58  MiscVal        1460 non-null   int64
 59  MoSold         1460 non-null   int64
 60  YrSold         1460 non-null   int64
 61  SaleType       1460 non-null   object
 62  SaleCondition  1460 non-null   object
 63  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(26)
memory usage: 730.1+ KB

In [55]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
X = df.select_dtypes(include=[np.number]).dropna()
X = X.drop(columns=['SalePrice'])
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
vif_data.sort_values(by="VIF", ascending=True)
vif_data

c:\Users\ahmed\datasci\env\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

          feature           VIF
0              Id  4.123920e+00
1      MSSubClass  4.825027e+00
2     LotFrontage  1.731328e+01
3         LotArea  3.458622e+00
4     OverallQual  7.333709e+01
5     OverallCond  4.966217e+01
6       YearBuilt  2.467113e+04
7    YearRemodAdd  2.452604e+04
8      MasVnrArea  1.944771e+00
9      BsmtFinSF1           inf
10     BsmtFinSF2           inf
11      BsmtUnfSF           inf
12    TotalBsmtSF           inf
13       1stFlrSF           inf
14       2ndFlrSF           inf
15   LowQualFinSF           inf
16      GrLivArea           inf
17   BsmtFullBath  3.658149e+00
18   BsmtHalfBath  1.215101e+00
19       FullBath  2.876728e+01
20       HalfBath  3.594813e+00
21   BedroomAbvGr  3.381667e+01
22   KitchenAbvGr  4.207555e+01
23   TotRmsAbvGrd  8.375455e+01
24     Fireplaces  3.028219e+00
25    GarageYrBlt  2.686365e+04
26     GarageCars  3.985939e+01
27     GarageArea  3.522618e+01
28     WoodDeckSF  1.945753e+00
29    OpenPorchSF  1.965951e+00
30  EnclosedPorch  1.486714e+00
31      3SsnPorch  1.048195e+00
32    ScreenPorch  1.240018e+00
33       PoolArea  1.196093e+00
34        MiscVal  1.120553e+00
35         MoSold  6.840926e+00
36         YrSold  2.529108e+04

In [56]:
#droping Bsmnt variables and leane the total one
df.drop(columns=['BsmtFinSF1','BsmtFinSF2','BsmtUnfSF'],inplace=True)

In [57]:
#vif of the variables
from statsmodels.stats.outliers_influence import variance_inflation_factor
X = df.select_dtypes(include=[np.number]).dropna()
X = X.drop(columns=['SalePrice'])
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
vif_data.sort_values(by="VIF", ascending=True)
vif_data

c:\Users\ahmed\datasci\env\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

          feature           VIF
0              Id  4.122564e+00
1      MSSubClass  4.821457e+00
2     LotFrontage  1.728856e+01
3         LotArea  3.420721e+00
4     OverallQual  7.235719e+01
5     OverallCond  4.900944e+01
6       YearBuilt  2.449855e+04
7    YearRemodAdd  2.413722e+04
8      MasVnrArea  1.917670e+00
9     TotalBsmtSF  2.963832e+01
10       1stFlrSF           inf
11       2ndFlrSF           inf
12   LowQualFinSF           inf
13      GrLivArea           inf
14   BsmtFullBath  2.163671e+00
15   BsmtHalfBath  1.149974e+00
16       FullBath  2.873214e+01
17       HalfBath  3.576970e+00
18   BedroomAbvGr  3.321196e+01
19   KitchenAbvGr  4.200394e+01
20   TotRmsAbvGrd  8.357355e+01
21     Fireplaces  3.017856e+00
22    GarageYrBlt  2.686348e+04
23     GarageCars  3.948445e+01
24     GarageArea  3.512671e+01
25     WoodDeckSF  1.941429e+00
26    OpenPorchSF  1.962982e+00
27  EnclosedPorch  1.481146e+00
28      3SsnPorch  1.047163e+00
29    ScreenPorch  1.235948e+00
30       PoolArea  1.184193e+00
31        MiscVal  1.119955e+00
32         MoSold  6.838670e+00
33         YrSold  2.523084e+04

In [58]:
#test in 5 sample if GrLivArea=1stFlrSF+2ndFlrSF+LowQualFinSF
df[['GrLivArea','1stFlrSF','2ndFlrSF','LowQualFinSF']].sample(5)

      GrLivArea  1stFlrSF  2ndFlrSF  LowQualFinSF
1285       1412       825       587             0
164        1616      1149       467             0
363         987       483       504             0
311         972       972         0             0
189        1593      1593         0             0

In [59]:
#GrLivArea = 1stFlrSF + 2ndFlrSF + LowQualFinSF
df.drop(columns=['1stFlrSF','2ndFlrSF','LowQualFinSF'],inplace=True)

In [60]:
X = df.select_dtypes(include=[np.number]).dropna()
X = X.drop(columns=['SalePrice'])
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
vif_data.sort_values(by="VIF", ascending=True)
vif_data

          feature           VIF
0              Id      4.104217
1      MSSubClass      4.670560
2     LotFrontage     17.166684
3         LotArea      3.420119
4     OverallQual     72.173412
5     OverallCond     48.875948
6       YearBuilt  23861.196532
7    YearRemodAdd  24027.051038
8      MasVnrArea      1.909605
9     TotalBsmtSF     17.974816
10      GrLivArea     68.971191
11   BsmtFullBath      2.161422
12   BsmtHalfBath      1.148834
13       FullBath     28.142707
14       HalfBath      2.965229
15   BedroomAbvGr     32.689923
16   KitchenAbvGr     39.795958
17   TotRmsAbvGrd     83.535555
18     Fireplaces      2.929672
19    GarageYrBlt  26425.235508
20     GarageCars     39.481399
21     GarageArea     35.096186
22     WoodDeckSF      1.937527
23    OpenPorchSF      1.954240
24  EnclosedPorch      1.471632
25      3SsnPorch      1.046296
26    ScreenPorch      1.231694
27       PoolArea      1.173739
28        MiscVal      1.114817
29         MoSold      6.831953
30         YrSold  24985.252424

In [61]:
# sample of GarageYrBlt YearBuilt YearRemodAdd	
df[['GarageYrBlt','YearRemodAdd','YearBuilt']].sample(10)

      GarageYrBlt  YearRemodAdd  YearBuilt
1433       2000.0          2000       2000
701        1969.0          1969       1969
1198       2001.0          2001       2001
1085       1992.0          1992       1992
1217       2009.0          2009       2009
1315       1969.0          1969       1969
0          2003.0          2003       2003
915        1970.0          1970       1970
535           NaN          1991       1910
611        1978.0          1978       1978

In [62]:
#drop GarageYrBlt
df.drop(columns=['GarageYrBlt'],inplace=True)
X = df.select_dtypes(include=[np.number]).dropna()
X = X.drop(columns=['SalePrice'])
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
vif_data.sort_values(by="VIF", ascending=True)
vif_data

          feature           VIF
0              Id      4.065352
1      MSSubClass      4.573681
2     LotFrontage     16.557460
3         LotArea      3.459283
4     OverallQual     67.290103
5     OverallCond     43.422825
6       YearBuilt  16515.763745
7    YearRemodAdd  20193.949256
8      MasVnrArea      1.863074
9     TotalBsmtSF     16.755485
10      GrLivArea     65.526747
11   BsmtFullBath      2.077644
12   BsmtHalfBath      1.137268
13       FullBath     25.934270
14       HalfBath      2.741893
15   BedroomAbvGr     29.749641
16   KitchenAbvGr     32.671924
17   TotRmsAbvGrd     82.526140
18     Fireplaces      2.802290
19     GarageCars     35.272339
20     GarageArea     31.021516
21     WoodDeckSF      1.889376
22    OpenPorchSF      1.847871
23  EnclosedPorch      1.483031
24      3SsnPorch      1.042712
25    ScreenPorch      1.215896
26       PoolArea      1.156975
27        MiscVal      1.086434
28         MoSold      6.770875
29         YrSold  20652.211608

In [63]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Alley',
       'LotShape', 'LotConfig', 'Neighborhood', 'Condition1', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'Foundation', 'BsmtQual', 'BsmtExposure', 'BsmtFinType1',
       'TotalBsmtSF', 'HeatingQC', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageFinish', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition',
       'SalePrice'],
      dtype='object')

In [64]:
# Create age at sale
df['AgeAtSale'] = df['YrSold'] - df['YearBuilt']


df['YearsSinceRemodel'] = df['YrSold'] - df['YearRemodAdd']


df['YearsSinceRemodel'] = df['YearsSinceRemodel'].clip(lower=0)


df = df.drop(columns=['YrSold', 'YearBuilt', 'YearRemodAdd'])

In [65]:
X = df.select_dtypes(include=[np.number]).dropna()
X = X.drop(columns=['SalePrice'])
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
vif_data.sort_values(by="VIF", ascending=True)
vif_data

              feature        VIF
0                  Id   3.989706
1          MSSubClass   4.513431
2         LotFrontage  16.050701
3             LotArea   3.459234
4         OverallQual  52.799297
5         OverallCond  32.124160
6          MasVnrArea   1.851372
7         TotalBsmtSF  16.320218
8           GrLivArea  60.547410
9        BsmtFullBath   2.066158
10       BsmtHalfBath   1.137227
11           FullBath  25.131106
12           HalfBath   2.672880
13       BedroomAbvGr  29.438343
14       KitchenAbvGr  28.881470
15       TotRmsAbvGrd  82.012927
16         Fireplaces   2.771212
17         GarageCars  35.217874
18         GarageArea  31.020662
19         WoodDeckSF   1.888937
20        OpenPorchSF   1.847180
21      EnclosedPorch   1.480346
22          3SsnPorch   1.042532
23        ScreenPorch   1.214217
24           PoolArea   1.156750
25            MiscVal   1.085331
26             MoSold   6.610060
27          AgeAtSale  10.206319
28  YearsSinceRemodel   4.257166

In [66]:
df[['OverallQual','OverallCond']].sample(10)

      OverallQual  OverallCond
380             5            6
1063            6            6
924             6            6
1182           10            5
260             6            5
535             5            7
104             7            4
1040            5            4
359             8            5
158             7            5

In [67]:
#drop GarageArea
df.drop(columns=['GarageCars'],inplace=True)

In [68]:
df[['BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd']].sample(10)

      BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd
321              4             1            10
368              2             1             7
669              2             1             5
1356             3             1             5
921              4             2             9
188              2             2             6
893              3             1             6
69               3             1             7
956              2             1             5
1044             4             1             9

In [69]:
# drop BedroomAbvGr KitchenAbvGr
df.drop(columns=['BedroomAbvGr','KitchenAbvGr','FullBath','TotRmsAbvGrd'],inplace=True)

In [70]:
#drop OverallCond
df.drop(columns=['OverallCond'],inplace=True)

In [71]:
#show all categorical columns
df.select_dtypes(include=['object']).columns

Index(['MSZoning', 'Alley', 'LotShape', 'LotConfig', 'Neighborhood',
       'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'Foundation', 'BsmtQual',
       'BsmtExposure', 'BsmtFinType1', 'HeatingQC', 'KitchenQual',
       'FireplaceQu', 'GarageType', 'GarageFinish', 'PoolQC', 'Fence',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [72]:
#drop GarageYrBlt
X = df.select_dtypes(include=[np.number]).dropna()
X = X.drop(columns=['SalePrice'])
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
vif_data.sort_values(by="VIF", ascending=True)
vif_data

              feature        VIF
0                  Id   3.843778
1          MSSubClass   3.602652
2         LotFrontage  14.373772
3             LotArea   3.447428
4         OverallQual  34.006239
5          MasVnrArea   1.811558
6         TotalBsmtSF  15.610521
7           GrLivArea  26.736275
8        BsmtFullBath   1.982429
9        BsmtHalfBath   1.101472
10           HalfBath   2.284060
11         Fireplaces   2.561744
12         GarageArea  10.357329
13         WoodDeckSF   1.870986
14        OpenPorchSF   1.798907
15      EnclosedPorch   1.420259
16          3SsnPorch   1.035572
17        ScreenPorch   1.202918
18           PoolArea   1.112363
19            MiscVal   1.073292
20             MoSold   6.379169
21          AgeAtSale   5.319674
22  YearsSinceRemodel   3.607620